---
- name: install openssh
  portage: package=net-misc/openssh
  tags: packages

- name: configure sshd
  template: >
    src=sshd_config.j2
    dest=/etc/ssh/sshd_config
    owner=root group=root mode=0600
    validate="/usr/sbin/sshd -t -f %s"
  notify: restart sshd
  tags: configuration

- name: start sshd (service module)
  service: name=sshd state=started
  when: not openssh_service_runit

- name: enable sshd (service module)
  service: name=sshd enabled=true
  when: not openssh_service_runit

- name: start sshd (runit module)
  runit: name=sshd state=started
  when: openssh_service_runit

- name: enable sshd (runit module)
  runit: name=sshd enabled=true
  when: openssh_service_runit
